const CSC_COUNTRIES = {
  ACR: "Ghana",
  AFG: "Afghanistan",
  AFR: "Kenya",
  ARO: "Argentina",
  ATT: "United States (AT&T)",
  AUT: "Switzerland",
  BGL: "Bulgaria",
  BMC: "Canada (Bell)",
  BNG: "Bangladesh",
  BRI: "Taiwan",
  BTU: "United Kingdom",
  CHC: "China",
  CHM: "China Mobile",
  CHN: "China",
  CHU: "China Unicom",
  CCT: "United States (Comcast)",
  CHA: "United States (Spectrum)",
  COO: "Colombia",
  DCM: "Japan (NTT Docomo)",
  DBT: "Germany",
  DKR: "Kenya",
  EGY: "Egypt",
  EON: "Trinidad and Tobago",
  EUX: "Europe",
  EUY: "Europe",
  FTM: "France",
  GLB: "Philippines",
  ILO: "Israel",
  KDI: "Japan (au)",
  KTC: "South Korea (KT)",
  INS: "India",
  ITV: "Italy",
  KOO: "South Korea",
  LUC: "South Korea (LG U+)",
  LUX: "Luxembourg",
  MID: "Middle East",
  MM1: "Singapore",
  MYM: "Thailand",
  NEE: "Nordic Countries",
  NPL: "Nepal",
  NZC: "New Zealand",
  PHE: "Spain",
  PHN: "Netherlands",
  ROM: "Romania",
  SEK: "Ukraine",
  SBM: "Japan (SoftBank)",
  SER: "Russia",
  SKC: "South Korea (SK Telecom)",
  SIN: "Singapore",
  SKZ: "Kazakhstan",
  SLK: "Sri Lanka",
  THL: "Thailand",
  TGY: "Hong Kong",
  TMB: "United States (T-Mobile)",
  TPA: "Panama",
  TUR: "Turkey",
  USC: "United States (US Cellular)",
  VZW: "United States (Verizon)",
  XAA: "United States",
  XAC: "Canada",
  XAR: "United States",
  XEF: "France",
  XFA: "South Africa",
  XFE: "South Africa",
  XJP: "Japan",
  XME: "Malaysia",
  XSA: "Australia",
  XSG: "United Arab Emirates",
  XSP: "Singapore",
  XXV: "Vietnam",
  ZTO: "Brazil"
};

export function countryForCsc(csc) {
  const normalized = String(csc || "").trim().toUpperCase();
  return CSC_COUNTRIES[normalized] || "Unknown";
}
